### ISSUE TITLE
Showing error in the new_png.php

### ISSUE THREAD

**Issue by GauravDuseja1** [adityarverma/railway-management-system#3]
Fatal error: Uncaught mysqli_sql_exception: Booking Not Possible!!!! in C:\xampp\htdocs\railway_management_system\new_png.php:60 Stack trace: #0 C:\xampp\htdocs\railway_management_system\new_png.php(60): mysqli->query('INSERT INTO res...') #1 {main} thrown in C:\xampp\htdocs\railway_management_system\new_png.php on line 60

**Comment by moulyamanjunath** [comment]
> Fatal error: Uncaught mysqli_sql_exception: Booking Not Possible!!!! in C:\xampp\htdocs\railway_management_system\new_png.php:60 Stack trace: #0 C:\xampp\htdocs\railway_management_system\new_png.php(60): mysqli->query('INSERT INTO res...') #1 {main} thrown in C:\xampp\htdocs\railway_management_system\new_png.php on line 6

we are also facing the same issue....did u resolve this issue?
